# AVIF version looks pretty gross actually...
# "./collection/images/cover.avif" = "https://cdn.mckayla.cloud/-/b4af983e411f43b892a93e8736fcdec8/cover.avif"
"./collection/images/cover.jpg"  = "https://cdn.mckayla.cloud/-/b4af983e411f43b892a93e8736fcdec8/cover.jpg"
# WebP version is intentionally missing, as it ends up being larger than the JPEG file.


# jQuery
"./dist/jquery/jquery-3.6.0.js"      = "https://code.jquery.com/jquery-3.6.0.js"
"./dist/jquery/jquery-3.6.0.min.js"  = "https://code.jquery.com/jquery-3.6.0.min.js"
"./dist/jquery/jquery-3.5.1.js"      = "https://code.jquery.com/jquery-3.5.1.js"
"./dist/jquery/jquery-3.5.1.min.js"  = "https://code.jquery.com/jquery-3.5.1.min.js"
"./dist/jquery/jquery-3.5.0.js"      = "https://code.jquery.com/jquery-3.5.0.js"
"./dist/jquery/jquery-3.5.0.min.js"  = "https://code.jquery.com/jquery-3.5.0.min.js"
"./dist/jquery/jquery-3.4.1.js"      = "https://code.jquery.com/jquery-3.4.1.js"
"./dist/jquery/jquery-3.4.1.min.js"  = "https://code.jquery.com/jquery-3.4.1.min.js"
"./dist/jquery/jquery-3.4.0.js"      = "https://code.jquery.com/jquery-3.4.0.js"
"./dist/jquery/jquery-3.4.0.min.js"  = "https://code.jquery.com/jquery-3.4.0.min.js"
"./dist/jquery/jquery-3.3.1.js"      = "https://code.jquery.com/jquery-3.3.1.js"
"./dist/jquery/jquery-3.3.1.min.js"  = "https://code.jquery.com/jquery-3.3.1.min.js"
"./dist/jquery/jquery-3.3.0.js"      = "https://code.jquery.com/jquery-3.3.0.js"
"./dist/jquery/jquery-3.3.0.min.js"  = "https://code.jquery.com/jquery-3.3.0.min.js"
"./dist/jquery/jquery-3.2.1.js"      = "https://code.jquery.com/jquery-3.2.1.js"
"./dist/jquery/jquery-3.2.1.min.js"  = "https://code.jquery.com/jquery-3.2.1.min.js"
"./dist/jquery/jquery-3.2.0.js"      = "https://code.jquery.com/jquery-3.2.0.js"
"./dist/jquery/jquery-3.2.0.min.js"  = "https://code.jquery.com/jquery-3.2.0.min.js"
"./dist/jquery/jquery-3.1.1.js"      = "https://code.jquery.com/jquery-3.1.1.js"
"./dist/jquery/jquery-3.1.1.min.js"  = "https://code.jquery.com/jquery-3.1.1.min.js"
"./dist/jquery/jquery-3.1.0.js"      = "https://code.jquery.com/jquery-3.1.0.js"
"./dist/jquery/jquery-3.1.0.min.js"  = "https://code.jquery.com/jquery-3.1.0.min.js"
"./dist/jquery/jquery-3.0.0.js"      = "https://code.jquery.com/jquery-3.0.0.js"
"./dist/jquery/jquery-3.0.0.min.js"  = "https://code.jquery.com/jquery-3.0.0.min.js"
"./dist/jquery/jquery-2.2.4.js"      = "https://code.jquery.com/jquery-2.2.4.js"
"./dist/jquery/jquery-2.2.4.min.js"  = "https://code.jquery.com/jquery-2.2.4.min.js"
"./dist/jquery/jquery-2.2.3.js"      = "https://code.jquery.com/jquery-2.2.3.js"
"./dist/jquery/jquery-2.2.3.min.js"  = "https://code.jquery.com/jquery-2.2.3.min.js"
"./dist/jquery/jquery-2.2.2.js"      = "https://code.jquery.com/jquery-2.2.2.js"
"./dist/jquery/jquery-2.2.2.min.js"  = "https://code.jquery.com/jquery-2.2.2.min.js"
"./dist/jquery/jquery-2.2.1.js"      = "https://code.jquery.com/jquery-2.2.1.js"
"./dist/jquery/jquery-2.2.1.min.js"  = "https://code.jquery.com/jquery-2.2.1.min.js"
"./dist/jquery/jquery-2.2.0.js"      = "https://code.jquery.com/jquery-2.2.0.js"
"./dist/jquery/jquery-2.2.0.min.js"  = "https://code.jquery.com/jquery-2.2.0.min.js"
"./dist/jquery/jquery-2.1.4.js"      = "https://code.jquery.com/jquery-2.1.4.js"
"./dist/jquery/jquery-2.1.4.min.js"  = "https://code.jquery.com/jquery-2.1.4.min.js"
"./dist/jquery/jquery-2.1.3.js"      = "https://code.jquery.com/jquery-2.1.3.js"
"./dist/jquery/jquery-2.1.3.min.js"  = "https://code.jquery.com/jquery-2.1.3.min.js"
"./dist/jquery/jquery-2.1.2.js"      = "https://code.jquery.com/jquery-2.1.2.js"
"./dist/jquery/jquery-2.1.2.min.js"  = "https://code.jquery.com/jquery-2.1.2.min.js"
"./dist/jquery/jquery-2.1.1.js"      = "https://code.jquery.com/jquery-2.1.1.js"
"./dist/jquery/jquery-2.1.1.min.js"  = "https://code.jquery.com/jquery-2.1.1.min.js"
"./dist/jquery/jquery-2.1.0.js"      = "https://code.jquery.com/jquery-2.1.0.js"
"./dist/jquery/jquery-2.1.0.min.js"  = "https://code.jquery.com/jquery-2.1.0.min.js"
"./dist/jquery/jquery-2.0.3.js"      = "https://code.jquery.com/jquery-2.0.3.js"
"./dist/jquery/jquery-2.0.3.min.js"  = "https://code.jquery.com/jquery-2.0.3.min.js"
"./dist/jquery/jquery-2.0.2.js"      = "https://code.jquery.com/jquery-2.0.2.js"
"./dist/jquery/jquery-2.0.2.min.js"  = "https://code.jquery.com/jquery-2.0.2.min.js"
"./dist/jquery/jquery-2.0.1.js"      = "https://code.jquery.com/jquery-2.0.1.js"
"./dist/jquery/jquery-2.0.1.min.js"  = "https://code.jquery.com/jquery-2.0.1.min.js"
"./dist/jquery/jquery-2.0.0.js"      = "https://code.jquery.com/jquery-2.0.0.js"
"./dist/jquery/jquery-2.0.0.min.js"  = "https://code.jquery.com/jquery-2.0.0.min.js"
"./dist/jquery/jquery-1.12.4.js"     = "https://code.jquery.com/jquery-1.12.4.js"
"./dist/jquery/jquery-1.12.4.min.js" = "https://code.jquery.com/jquery-1.12.4.min.js"
"./dist/jquery/jquery-1.12.3.js"     = "https://code.jquery.com/jquery-1.12.3.js"
"./dist/jquery/jquery-1.12.3.min.js" = "https://code.jquery.com/jquery-1.12.3.min.js"
"./dist/jquery/jquery-1.12.2.js"     = "https://code.jquery.com/jquery-1.12.2.js"
"./dist/jquery/jquery-1.12.2.min.js" = "https://code.jquery.com/jquery-1.12.2.min.js"
"./dist/jquery/jquery-1.12.1.js"     = "https://code.jquery.com/jquery-1.12.1.js"
"./dist/jquery/jquery-1.12.1.min.js" = "https://code.jquery.com/jquery-1.12.1.min.js"
"./dist/jquery/jquery-1.12.0.js"     = "https://code.jquery.com/jquery-1.12.0.js"
"./dist/jquery/jquery-1.12.0.min.js" = "https://code.jquery.com/jquery-1.12.0.min.js"
"./dist/jquery/jquery-1.11.3.js"     = "https://code.jquery.com/jquery-1.11.3.js"
"./dist/jquery/jquery-1.11.3.min.js" = "https://code.jquery.com/jquery-1.11.3.min.js"
"./dist/jquery/jquery-1.11.2.js"     = "https://code.jquery.com/jquery-1.11.2.js"
"./dist/jquery/jquery-1.11.2.min.js" = "https://code.jquery.com/jquery-1.11.2.min.js"
"./dist/jquery/jquery-1.11.1.js"     = "https://code.jquery.com/jquery-1.11.1.js"
"./dist/jquery/jquery-1.11.1.min.js" = "https://code.jquery.com/jquery-1.11.1.min.js"
"./dist/jquery/jquery-1.11.0.js"     = "https://code.jquery.com/jquery-1.11.0.js"
"./dist/jquery/jquery-1.11.0.min.js" = "https://code.jquery.com/jquery-1.11.0.min.js"
"./dist/jquery/jquery-1.10.2.js"     = "https://code.jquery.com/jquery-1.10.2.js"
"./dist/jquery/jquery-1.10.2.min.js" = "https://code.jquery.com/jquery-1.10.2.min.js"
"./dist/jquery/jquery-1.10.1.js"     = "https://code.jquery.com/jquery-1.10.1.js"
"./dist/jquery/jquery-1.10.1.min.js" = "https://code.jquery.com/jquery-1.10.1.min.js"
"./dist/jquery/jquery-1.10.0.js"     = "https://code.jquery.com/jquery-1.10.0.js"
"./dist/jquery/jquery-1.10.0.min.js" = "https://code.jquery.com/jquery-1.10.0.min.js"
"./dist/jquery/jquery-1.9.1.js"      = "https://code.jquery.com/jquery-1.9.1.js"
"./dist/jquery/jquery-1.9.1.min.js"  = "https://code.jquery.com/jquery-1.9.1.min.js"
"./dist/jquery/jquery-1.9.0.js"      = "https://code.jquery.com/jquery-1.9.0.js"
"./dist/jquery/jquery-1.9.0.min.js"  = "https://code.jquery.com/jquery-1.9.0.min.js"
"./dist/jquery/jquery-1.8.3.js"      = "https://code.jquery.com/jquery-1.8.3.js"
"./dist/jquery/jquery-1.8.3.min.js"  = "https://code.jquery.com/jquery-1.8.3.min.js"
"./dist/jquery/jquery-1.8.2.js"      = "https://code.jquery.com/jquery-1.8.2.js"
"./dist/jquery/jquery-1.8.2.min.js"  = "https://code.jquery.com/jquery-1.8.2.min.js"
"./dist/jquery/jquery-1.8.1.js"      = "https://code.jquery.com/jquery-1.8.1.js"
"./dist/jquery/jquery-1.8.1.min.js"  = "https://code.jquery.com/jquery-1.8.1.min.js"
"./dist/jquery/jquery-1.8.0.js"      = "https://code.jquery.com/jquery-1.8.0.js"
"./dist/jquery/jquery-1.8.0.min.js"  = "https://code.jquery.com/jquery-1.8.0.min.js"
"./dist/jquery/jquery-1.7.2.js"      = "https://code.jquery.com/jquery-1.7.2.js"
"./dist/jquery/jquery-1.7.2.min.js"  = "https://code.jquery.com/jquery-1.7.2.min.js"
"./dist/jquery/jquery-1.7.1.js"      = "https://code.jquery.com/jquery-1.7.1.js"
"./dist/jquery/jquery-1.7.1.min.js"  = "https://code.jquery.com/jquery-1.7.1.min.js"
"./dist/jquery/jquery-1.7.0.js"      = "https://code.jquery.com/jquery-1.7.0.js"
"./dist/jquery/jquery-1.7.0.min.js"  = "https://code.jquery.com/jquery-1.7.0.min.js"
"./dist/jquery/jquery-1.6.4.js"      = "https://code.jquery.com/jquery-1.6.4.js"
"./dist/jquery/jquery-1.6.4.min.js"  = "https://code.jquery.com/jquery-1.6.4.min.js"
"./dist/jquery/jquery-1.6.3.js"      = "https://code.jquery.com/jquery-1.6.3.js"
"./dist/jquery/jquery-1.6.3.min.js"  = "https://code.jquery.com/jquery-1.6.3.min.js"
"./dist/jquery/jquery-1.6.2.js"      = "https://code.jquery.com/jquery-1.6.2.js"
"./dist/jquery/jquery-1.6.2.min.js"  = "https://code.jquery.com/jquery-1.6.2.min.js"
"./dist/jquery/jquery-1.6.1.js"      = "https://code.jquery.com/jquery-1.6.1.js"
"./dist/jquery/jquery-1.6.1.min.js"  = "https://code.jquery.com/jquery-1.6.1.min.js"
"./dist/jquery/jquery-1.6.js"        = "https://code.jquery.com/jquery-1.6.js"
"./dist/jquery/jquery-1.6.min.js"    = "https://code.jquery.com/jquery-1.6.min.js"
"./dist/jquery/jquery-1.5.2.js"      = "https://code.jquery.com/jquery-1.5.2.js"
"./dist/jquery/jquery-1.5.2.min.js"  = "https://code.jquery.com/jquery-1.5.2.min.js"
"./dist/jquery/jquery-1.5.1.js"      = "https://code.jquery.com/jquery-1.5.1.js"
"./dist/jquery/jquery-1.5.1.min.js"  = "https://code.jquery.com/jquery-1.5.1.min.js"
"./dist/jquery/jquery-1.5.js"        = "https://code.jquery.com/jquery-1.5.js"
"./dist/jquery/jquery-1.5.min.js"    = "https://code.jquery.com/jquery-1.5.min.js"
"./dist/jquery/jquery-1.4.4.js"      = "https://code.jquery.com/jquery-1.4.4.js"
"./dist/jquery/jquery-1.4.4.min.js"  = "https://code.jquery.com/jquery-1.4.4.min.js"
"./dist/jquery/jquery-1.4.3.js"      = "https://code.jquery.com/jquery-1.4.3.js"
"./dist/jquery/jquery-1.4.3.min.js"  = "https://code.jquery.com/jquery-1.4.3.min.js"
"./dist/jquery/jquery-1.4.2.js"      = "https://code.jquery.com/jquery-1.4.2.js"
"./dist/jquery/jquery-1.4.2.min.js"  = "https://code.jquery.com/jquery-1.4.2.min.js"
"./dist/jquery/jquery-1.4.1.js"      = "https://code.jquery.com/jquery-1.4.1.js"
"./dist/jquery/jquery-1.4.1.min.js"  = "https://code.jquery.com/jquery-1.4.1.min.js"
"./dist/jquery/jquery-1.4.js"        = "https://code.jquery.com/jquery-1.4.js"
"./dist/jquery/jquery-1.4.min.js"    = "https://code.jquery.com/jquery-1.4.min.js"
"./dist/jquery/jquery-1.3.2.js"      = "https://code.jquery.com/jquery-1.3.2.js"
"./dist/jquery/jquery-1.3.2.min.js"  = "https://code.jquery.com/jquery-1.3.2.min.js"
"./dist/jquery/jquery-1.3.1.js"      = "https://code.jquery.com/jquery-1.3.1.js"
"./dist/jquery/jquery-1.3.1.min.js"  = "https://code.jquery.com/jquery-1.3.1.min.js"
"./dist/jquery/jquery-1.3.js"        = "https://code.jquery.com/jquery-1.3.js"
"./dist/jquery/jquery-1.3.min.js"    = "https://code.jquery.com/jquery-1.3.min.js"
"./dist/jquery/jquery-1.2.6.js"      = "https://code.jquery.com/jquery-1.2.6.js"
"./dist/jquery/jquery-1.2.6.min.js"  = "https://code.jquery.com/jquery-1.2.6.min.js"
"./dist/jquery/jquery-1.2.5.js"      = "https://code.jquery.com/jquery-1.2.5.js"
"./dist/jquery/jquery-1.2.5.min.js"  = "https://code.jquery.com/jquery-1.2.5.min.js"
"./dist/jquery/jquery-1.2.4.js"      = "https://code.jquery.com/jquery-1.2.4.js"
"./dist/jquery/jquery-1.2.4.min.js"  = "https://code.jquery.com/jquery-1.2.4.min.js"
"./dist/jquery/jquery-1.2.3.js"      = "https://code.jquery.com/jquery-1.2.3.js"
"./dist/jquery/jquery-1.2.3.min.js"  = "https://code.jquery.com/jquery-1.2.3.min.js"
"./dist/jquery/jquery-1.2.2.js"      = "https://code.jquery.com/jquery-1.2.2.js"
"./dist/jquery/jquery-1.2.2.min.js"  = "https://code.jquery.com/jquery-1.2.2.min.js"
"./dist/jquery/jquery-1.2.1.js"      = "https://code.jquery.com/jquery-1.2.1.js"
"./dist/jquery/jquery-1.2.1.min.js"  = "https://code.jquery.com/jquery-1.2.1.min.js"
"./dist/jquery/jquery-1.2.js"        = "https://code.jquery.com/jquery-1.2.js"
"./dist/jquery/jquery-1.2.min.js"    = "https://code.jquery.com/jquery-1.2.min.js"
"./dist/jquery/jquery-1.1.4.js"      = "https://code.jquery.com/jquery-1.1.4.js"
"./dist/jquery/jquery-1.1.3.js"      = "https://code.jquery.com/jquery-1.1.3.js"
"./dist/jquery/jquery-1.1.2.js"      = "https://code.jquery.com/jquery-1.1.2.js"
"./dist/jquery/jquery-1.1.1.js"      = "https://code.jquery.com/jquery-1.1.1.js"
"./dist/jquery/jquery-1.1.js"        = "https://code.jquery.com/jquery-1.1.js"
"./dist/jquery/jquery-1.0.4.js"      = "https://code.jquery.com/jquery-1.0.4.js"
"./dist/jquery/jquery-1.0.3.js"      = "https://code.jquery.com/jquery-1.0.3.js"
"./dist/jquery/jquery-1.0.2.js"      = "https://code.jquery.com/jquery-1.0.2.js"
"./dist/jquery/jquery-1.0.1.js"      = "https://code.jquery.com/jquery-1.0.1.js"
"./dist/jquery/jquery-1.0.js"        = "https://code.jquery.com/jquery-1.0.js"


# MooTools
"./dist/mootools/mootools-1.6.0.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.js"
"./dist/mootools/mootools-1.6.0.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js"
"./dist/mootools/mootools-1.5.2.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.2/mootools.js"
"./dist/mootools/mootools-1.5.2.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.2/mootools.min.js"
"./dist/mootools/mootools-1.5.1.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.1/mootools.js"
"./dist/mootools/mootools-1.5.1.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.1/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.5.0.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.0/mootools.js"
"./dist/mootools/mootools-1.5.0.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.5.0/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.5.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools.js"
"./dist/mootools/mootools-1.4.5.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.4.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.4/mootools.js"
"./dist/mootools/mootools-1.4.4.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.4/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.3.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.3/mootools.js"
"./dist/mootools/mootools-1.4.3.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.3/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.2.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.2/mootools.js"
"./dist/mootools/mootools-1.4.2.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.2/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.1.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.1/mootools.js"
"./dist/mootools/mootools-1.4.1.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.1/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.4.0.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.0/mootools.js"
"./dist/mootools/mootools-1.4.0.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.4.0/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.3.2.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.2/mootools.js"
"./dist/mootools/mootools-1.3.2.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.2/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.3.1.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.1/mootools.js"
"./dist/mootools/mootools-1.3.1.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.1/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.3.0.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.0/mootools.js"
"./dist/mootools/mootools-1.3.0.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.3.0/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.2.5.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.5/mootools.js"
"./dist/mootools/mootools-1.2.5.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.5/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.2.4.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools.js"
"./dist/mootools/mootools-1.2.4.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.2.3.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.3/mootools.js"
"./dist/mootools/mootools-1.2.3.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.3/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.2.2.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.2/mootools.js"
"./dist/mootools/mootools-1.2.2.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.2/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.2.1.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.1/mootools.js"
"./dist/mootools/mootools-1.2.1.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.2.1/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.1.2.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.1.2/mootools.js"
"./dist/mootools/mootools-1.1.2.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.1.2/mootools-yui-compressed.js"
"./dist/mootools/mootools-1.1.1.js"     = "https://ajax.googleapis.com/ajax/libs/mootools/1.1.1/mootools.js"
"./dist/mootools/mootools-1.1.1.min.js" = "https://ajax.googleapis.com/ajax/libs/mootools/1.1.1/mootools-yui-compressed.js"


# Prototype
"./dist/prototype/prototype-1.7.3.js"   = "https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"
"./dist/prototype/prototype-1.7.2.js"   = "https://ajax.googleapis.com/ajax/libs/prototype/1.7.2.0/prototype.js"
"./dist/prototype/prototype-1.7.1.js"   = "https://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js"
"./dist/prototype/prototype-1.7.js"     = "https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"
"./dist/prototype/prototype-1.6.1.js"   = "http://prototypejs.org/assets/2009/8/31/prototype.js"
"./dist/prototype/prototype-1.6.0.3.js" = "http://prototypejs.org/assets/2008/9/29/prototype-1.6.0.3.js"
"./dist/prototype/prototype-1.6.0.2.js" = "http://prototypejs.org/assets/2008/1/25/prototype-1.6.0.2.js"
"./dist/prototype/prototype-1.6.js"     = "http://prototypejs.org/assets/2007/11/6/prototype.js"
"./dist/prototype/prototype-1.5.1.2.js" = "http://prototypejs.org/assets/2008/1/25/prototype-1.5.1.2.js"
"./dist/prototype/prototype-1.5.1.1.js" = "http://prototypejs.org/assets/2007/6/20/prototype.js"
"./dist/prototype/prototype-1.5.1.js"   = "http://prototypejs.org/assets/2007/5/1/prototype.js"
"./dist/prototype/prototype-1.5.js"     = "http://prototypejs.org/assets/2007/1/18/prototype.js"

# Prototype.Scriptaculous
"./dist/prototype/scripty-2.0.0-b1.zip"   = "http://scripty2.com/download/scripty2-2.0.0_b1.zip"
"./dist/prototype/scriptaculous-1.9.0.js" = "https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"
"./dist/prototype/scriptaculous-1.8.3.js" = "https://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.3/scriptaculous.js"
"./dist/prototype/scriptaculous-1.8.2.js" = "https://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.2/scriptaculous.js"
"./dist/prototype/scriptaculous-1.8.1.js" = "https://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.1/scriptaculous.js"
