name: deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
          key: betty-cargo-${{matrix.rust-version}}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: betty-cargo-${{matrix.rust-version}}-

      - run: cargo install betty

      - run: betty

      - uses: actions/upload-pages-artifact@v1
        name: Upload static assets
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
