name: deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - run: echo $RUNNER_TOOL_CACHE; ls $RUNNER_TOOL_CACHE

      - run: |
          curl -sSL https://github.com/aslilac/betty/releases/download/v0.1.1/betty-v0.1.1-x86_64-unknown-linux-gnu.tar.gz | \
            tar -xvz -C $RUNNER_TOOL_CACHE
        name: betty (prepare)

      - uses: actions/cache@v4
        name: cache
        with:
          path: dist/
          key: betty-dist

      - run: betty

      - uses: actions/upload-pages-artifact@v1
        name: upload
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
